# Generated by Django 5.2 on 2026-01-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='nombre_jugador',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='reserva',
            name='codigo_cancelacion',
            field=models.CharField(default='ABC123456', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20),
        ),
    ]
