# Generated by Django 5.2 on 2026-01-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_rename_nombre_jugador_reserva_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='reserva',
            name='codigo_cancelacion',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
